from setuptools import setup, find_packages

setup(
    name="hypoxify-annotate",
    version="0.1.0",
    packages=find_packages(),
    install_requires=[
        "numpy>=1.21.0",
        "scipy>=1.7.0",
        "pandas>=1.3.0",
        "matplotlib>=3.5.0",
        "scikit-image>=0.19.0",
        "pillow>=9.0.0",
        "streamlit>=1.25.0",
        "opencv-python>=4.5.0",
        "h5py>=3.0.0",
        "pydicom>=2.3.0",
        "torch>=1.9.0",
        "segment-anything>=1.0.0",
    ],
    author="Anie Udofia",
    author_email="mails4anietor@gmail.com",
    description="Physics-informed annotation for microwave, thermoacoustic, and biomedical imaging",
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.9",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Medical Science Apps.",
    ],
    python_requires=">=3.8",
)
